# Generated by Django 5.1.5 on 2025-02-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=18, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, choices=[('HS', 'High School'), ('B', 'Bachelor'), ('M', 'Master'), ('P', 'PhD')], default='HS', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='+996', max_length=15, null=True),
        ),
    ]
