# Generated by Django 5.1.5 on 2025-02-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('детская', 'Детская'), ('подростковая', 'Подростковая'), ('взрослая', 'Взрослая')], max_length=20)),
            ],
        ),
    ]
