# Generated by Django 5.1.5 on 2025-02-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookmodel_genre_bookmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
