# Generated by Django 5.1.5 on 2025-02-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_comment_book_delete_clothing_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
